# Generated by Django 3.2.19 on 2023-06-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230608_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание тега'),
        ),
    ]
